<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'StackoverflowApi\Client\Client'                         => __DIR__ . '/Client/Client.php',
    'StackoverflowApi\Client\DataTransformer'                => __DIR__ . '/Client/DataTransformer.php',
    'StackoverflowApi\Client\Response'                       => __DIR__ . '/Client/Response.php',
    'StackoverflowApi\Entity\ApiResponse'                    => __DIR__ . '/Entity/ApiResponse.php',
    'StackoverflowApi\Entity\ApiResponseInterface'           => __DIR__ . '/Entity/ApiResponseInterface.php',
    'StackoverflowApi\Entity\JobData'                        => __DIR__ . '/Entity/JobData.php',
    'StackoverflowApi\Entity\JobDataInterface'               => __DIR__ . '/Entity/JobDataInterface.php',
    'StackoverflowApi\Factory\Client\ClientFactory'          => __DIR__ . '/Factory/Client/ClientFactory.php',
    'StackoverflowApi\Factory\Client\DataTransformerFactory' => __DIR__ . '/Factory/Client/DataTransformerFactory.php',
    'StackoverflowApi\Factory\Listener\JobsListenerFactory'  => __DIR__ . '/Factory/Listener/JobsListenerFactory.php',
    'StackoverflowApi\Factory\Service\JobsManagerFactory'    => __DIR__ . '/Factory/Service/JobsManagerFactory.php',
    'StackoverflowApi\Listener\JobsListener'                 => __DIR__ . '/Listener/JobsListener.php',
    'StackoverflowApi\Options\ModuleOptions'                 => __DIR__ . '/Options/ModuleOptions.php',
    'StackoverflowApi\Service\JobsManager'                   => __DIR__ . '/Service/JobsManager.php',
);
